erDiagram

    tb_log_erros {
        NUMBER id PK
        VARCHAR2 nome_procedure
        VARCHAR2 nome_usuario
        TIMESTAMP data_erro
        NUMBER codigo_erro
        VARCHAR2 mensagem_erro
    }

    tutor {
        VARCHAR2 id PK
        VARCHAR2 nome
        VARCHAR2 email
        VARCHAR2 cpf
        VARCHAR2 telefone
        DATE data_nascimento
        VARCHAR2 sexo
        VARCHAR2 logradouro
        VARCHAR2 numero
        VARCHAR2 bairro
        VARCHAR2 cidade
        VARCHAR2 estado
        VARCHAR2 cep
        TIMESTAMP criado_em
    }

    animal {
        VARCHAR2 id PK
        VARCHAR2 nome
        VARCHAR2 especie
        VARCHAR2 raca
        VARCHAR2 porte
        VARCHAR2 cor
        VARCHAR2 sexo
        DATE data_nascimento
        VARCHAR2 observacao
        VARCHAR2 tutor_id FK
        TIMESTAMP criado_em
    }

    clinica {
        VARCHAR2 id PK
        VARCHAR2 nome
        VARCHAR2 cnpj
        VARCHAR2 telefone
        VARCHAR2 email
        VARCHAR2 logradouro
        VARCHAR2 numero
        VARCHAR2 bairro
        VARCHAR2 cidade
        VARCHAR2 estado
        VARCHAR2 cep
        TIMESTAMP criado_em
    }

    veterinario {
        VARCHAR2 id PK
        VARCHAR2 nome
        VARCHAR2 crmv
        VARCHAR2 especialidade
        VARCHAR2 email
        VARCHAR2 cpf
        VARCHAR2 telefone
        VARCHAR2 sexo
        DATE data_nascimento
        VARCHAR2 clinica_id FK
        VARCHAR2 logradouro
        VARCHAR2 numero
        VARCHAR2 bairro
        VARCHAR2 cidade
        VARCHAR2 estado
        VARCHAR2 cep
        TIMESTAMP criado_em
    }

    evento_clinico {
        VARCHAR2 id PK
        DATE data
        VARCHAR2 hora
        VARCHAR2 tipo_evento
        VARCHAR2 descricao
        VARCHAR2 veterinario_id FK
        VARCHAR2 animal_id FK
        VARCHAR2 clinica_id FK
        TIMESTAMP criado_em
    }

    pagamento {
        VARCHAR2 id PK
        VARCHAR2 forma_pagamento
        NUMBER valor
        VARCHAR2 status_pagamento
        DATE data_pagamento
        VARCHAR2 descricao
        VARCHAR2 observacao
        VARCHAR2 evento_clinico_id FK
        TIMESTAMP criado_em
    }

    tutor         ||--o{ animal          : "possui"
    animal        ||--o{ evento_clinico  : "participa"
    clinica       ||--o{ veterinario     : "emprega"
    clinica       ||--o{ evento_clinico  : "sedia"
    veterinario   ||--o{ evento_clinico  : "atende"
    evento_clinico ||--o| pagamento      : "gera"
